---
title: "Group Document"
format: html
---

# The amazingly fantastic and cool TAs

## Jonathan

## New feature

Yes, this is me

```{r}

print('Welcome Saturday')
```


```{r}
# This is second work!
print('Unwelcome Monday')
```

## Puck

Bananas

```{r}
1+1
```

## Amanda

Amanda's personal section.

Hello, and welcome to my section.

Let's run some code!

```{r}
library("tidyverse")
df <- tibble(x = c(1,2,3)) |> 
  mutate(y = x*2)
```

```{r}
df2 <- df |> 
  mutate(z = y*2)
```

## New analysis

Very new and bananas analysis go here.

```{r}
df3 <- df2 |> 
  group_by(x) |> 
  summarise(x, mean(y))
```

## Frederik

Frederik's personal section. We are doing work, yes.

```{r}
library(tidyverse)
ggplot(data = data.frame(x = rnorm(100),
                         y = rnorm(100)),
       mapping = aes(x=x,
                     y=y)) + 
  geom_point() +
  theme_minimal()
```

### New stuff (pretty cool)
```{r}
library(tidyverse)
ggplot(data = data.frame(x = rchisq(100, 0, 50),
                         y = rbeta(100, 1, 8)),
       mapping = aes(x=x,
                     y=y)) + 
  geom_point() +
  theme_minimal()
```
